[package]
name = "day7"
version = "0.1.0"
authors = ["Victor Sonck <victor.sonck@ml6.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.7"
itertools = "0.8.2"
permutohedron = "0.2.4"